### ISSUE TITLE
Filtrar por dias de trabalho em um mês

### ISSUE THREAD

**Issue by alvesisaque** [Dulce-Work-Schedule/2018.1-Dulce_Schedule#27]
Eu, como plantonista, desejo visualizar minha escala, a fim de ver meus horários de trabalho filtrados por um dia de trabalho em um mês.

Atributos:
- Data Início
- Data Fim
- Horário Início
- Horário Fim
- Setor
- Plantonista

Validações:
- [Semana] O intervalo deve ser de segunda a domingo (7 dias)

**Comment by egewarth** [comment]
Issue não vai ser feita mais por decisão do grupo
