### ISSUE TITLE
Filtrar por horários de trabalho em uma semana

### ISSUE THREAD

**Issue by alvesisaque** [Dulce-Work-Schedule/2018.1-Dulce_Schedule#28]
Eu, como plantonista, desejo visualizar minha escala, a fim de ver meus horários de trabalho filtrado por horários de trabalho em uma semana.

Atributos:
- Data Início
- Data Fim
- Horário Início
- Horário Fim
- Setor
- Plantonista

Validações:
- [Semana] O intervalo deve ser de segunda a domingo (7 dias)

**Comment by egewarth** [comment]
Essa issue não vai ser mais implementada por decisão conjunta
