### ISSUE TITLE
Filtrar por horários de trabalho em um dia

### ISSUE THREAD

**Issue by eliseuegewarth** [Dulce-Work-Schedule/2018.1-Dulce_Schedule#29]
Nessa issue será realizado:
- Filtrar por horários de trabalho em um dia

Atributos:
- Data Início
- Data Fim
- Horário Início
- Horário Fim
- Setor
- Plantonista

Critérios de aceitação:
- O dia deve ser valido (máximo 31)

**Comment by egewarth** [comment]
Essa issue não será mais implementada por decisão conjunta.
