### ISSUE TITLE
Implementar validações para o mês e horário válido ao criar uma escala.

### ISSUE THREAD

**Issue by alvesisaque** [Dulce-Work-Schedule/2018.1-Dulce_Schedule#35]
Nessa issue deverá ser feito as seguintes validações: 

- Um horário estar em um dia/mês/ano válido.
- Um plantonista pode possuir apenas um plantão por horário (conflito de horários).

**Comment by egewarth** [comment]
Feito na branch 31_33_34_35_create_schedule
