### ISSUE TITLE
Testes unitários

### ISSUE THREAD

**Issue by egewarth** [Dulce-Work-Schedule/2018.1-Dulce_Schedule#49]
Nessa issue deve ser feito:
- Testes unitários das classes:
- [ ] listByProfile
- [ ] listYearByProfile
- [ ] listYearBySector

**Comment by egewarth** [comment]
@alvesisaque , veja como ficará a organização dessa issue devido ser implementada por um colaborador externo

**Comment by alvesisaque** [comment]
@egewarth Ok, assim que possível eu olho
